server {
    listen       80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }

    # GLB files need explicit mime type
    location ~* \.glb$ {
        root /usr/share/nginx/html;
        default_type model/gltf-binary;
        add_header Cache-Control "public, max-age=86400";
    }

    gzip on;
    gzip_types text/plain text/css application/javascript audio/mpeg;
}
